/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables.tables.records;


import com.jin.jooq.tables.tables.Individual;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndividualRecord extends UpdatableRecordImpl<IndividualRecord> implements Record10<Integer, String, String, String, String, String, Date, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 9257673;

    /**
     * Setter for <code>cyui.individual.ID</code>. 主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cyui.individual.ID</code>. 主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cyui.individual.USER_NAME</code>. 用户名
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cyui.individual.USER_NAME</code>. 用户名
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cyui.individual.USER_PASSWORD</code>. 密码(MD5加密)
     */
    public void setUserPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cyui.individual.USER_PASSWORD</code>. 密码(MD5加密)
     */
    public String getUserPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cyui.individual.USER_NICE_NAME</code>. 昵称
     */
    public void setUserNiceName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cyui.individual.USER_NICE_NAME</code>. 昵称
     */
    public String getUserNiceName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cyui.individual.USER_IMG_URL</code>. 图像地址
     */
    public void setUserImgUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cyui.individual.USER_IMG_URL</code>. 图像地址
     */
    public String getUserImgUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cyui.individual.PHONE_NUMBER</code>. 手机号
     */
    public void setPhoneNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cyui.individual.PHONE_NUMBER</code>. 手机号
     */
    public String getPhoneNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cyui.individual.USER_BIRTHDAY</code>. 生日
     */
    public void setUserBirthday(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>cyui.individual.USER_BIRTHDAY</code>. 生日
     */
    public Date getUserBirthday() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>cyui.individual.UTIME</code>. 修改时间
     */
    public void setUtime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>cyui.individual.UTIME</code>. 修改时间
     */
    public Timestamp getUtime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>cyui.individual.CTIME</code>. 创建时间
     */
    public void setCtime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>cyui.individual.CTIME</code>. 创建时间
     */
    public Timestamp getCtime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>cyui.individual.ROLE</code>. 1,超级管理员 2，管理  3，普通用户
     */
    public void setRole(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>cyui.individual.ROLE</code>. 1,超级管理员 2，管理  3，普通用户
     */
    public String getRole() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, Date, Timestamp, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, Date, Timestamp, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Individual.INDIVIDUAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Individual.INDIVIDUAL.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Individual.INDIVIDUAL.USER_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Individual.INDIVIDUAL.USER_NICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Individual.INDIVIDUAL.USER_IMG_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Individual.INDIVIDUAL.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return Individual.INDIVIDUAL.USER_BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Individual.INDIVIDUAL.UTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Individual.INDIVIDUAL.CTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Individual.INDIVIDUAL.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserNiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component7() {
        return getUserBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserNiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getUserBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value3(String value) {
        setUserPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value4(String value) {
        setUserNiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value5(String value) {
        setUserImgUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value6(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value7(Date value) {
        setUserBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value8(Timestamp value) {
        setUtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value9(Timestamp value) {
        setCtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord value10(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndividualRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Date value7, Timestamp value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualRecord
     */
    public IndividualRecord() {
        super(Individual.INDIVIDUAL);
    }

    /**
     * Create a detached, initialised IndividualRecord
     */
    public IndividualRecord(Integer id, String userName, String userPassword, String userNiceName, String userImgUrl, String phoneNumber, Date userBirthday, Timestamp utime, Timestamp ctime, String role) {
        super(Individual.INDIVIDUAL);

        set(0, id);
        set(1, userName);
        set(2, userPassword);
        set(3, userNiceName);
        set(4, userImgUrl);
        set(5, phoneNumber);
        set(6, userBirthday);
        set(7, utime);
        set(8, ctime);
        set(9, role);
    }
}
