/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables.tables.records;


import com.jin.jooq.tables.tables.Register;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisterRecord extends UpdatableRecordImpl<RegisterRecord> implements Record6<Integer, String, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 2095354350;

    /**
     * Setter for <code>cyui.register.registerNo</code>. 主键，唯一标识
     */
    public void setRegisterno(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cyui.register.registerNo</code>. 主键，唯一标识
     */
    public Integer getRegisterno() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cyui.register.registerName</code>. 名称，必填
     */
    public void setRegistername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cyui.register.registerName</code>. 名称，必填
     */
    public String getRegistername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cyui.register.role</code>. 角色，0-超级管理员，1-管理员，2-普通用户
     */
    public void setRole(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cyui.register.role</code>. 角色，0-超级管理员，1-管理员，2-普通用户
     */
    public Integer getRole() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cyui.register.age</code>. 年龄
     */
    public void setAge(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>cyui.register.age</code>. 年龄
     */
    public Integer getAge() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>cyui.register.address</code>. 地址
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cyui.register.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cyui.register.status</code>. 状态，0-开启，1-关闭
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>cyui.register.status</code>. 状态，0-开启，1-关闭
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Register.REGISTER.REGISTERNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Register.REGISTER.REGISTERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Register.REGISTER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Register.REGISTER.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Register.REGISTER.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Register.REGISTER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRegisterno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRegistername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRegisterno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRegistername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord value1(Integer value) {
        setRegisterno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord value2(String value) {
        setRegistername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord value3(Integer value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord value4(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RegisterRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisterRecord
     */
    public RegisterRecord() {
        super(Register.REGISTER);
    }

    /**
     * Create a detached, initialised RegisterRecord
     */
    public RegisterRecord(Integer registerno, String registername, Integer role, Integer age, String address, Integer status) {
        super(Register.REGISTER);

        set(0, registerno);
        set(1, registername);
        set(2, role);
        set(3, age);
        set(4, address);
        set(5, status);
    }
}
