/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables;


import com.jin.jooq.tables.tables.Individual;
import com.jin.jooq.tables.tables.Register;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cyui extends SchemaImpl {

    private static final long serialVersionUID = 827818640;

    /**
     * The reference instance of <code>cyui</code>
     */
    public static final Cyui CYUI = new Cyui();

    /**
     * The table <code>cyui.individual</code>.
     */
    public final Individual INDIVIDUAL = com.jin.jooq.tables.tables.Individual.INDIVIDUAL;

    /**
     * The table <code>cyui.register</code>.
     */
    public final Register REGISTER = com.jin.jooq.tables.tables.Register.REGISTER;

    /**
     * No further instances allowed
     */
    private Cyui() {
        super("cyui", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Individual.INDIVIDUAL,
            Register.REGISTER);
    }
}
