/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables;


import com.jin.jooq.tables.tables.Individual;
import com.jin.jooq.tables.tables.Register;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>cyui</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index INDIVIDUAL_PRIMARY = Indexes0.INDIVIDUAL_PRIMARY;
    public static final Index REGISTER_PRIMARY = Indexes0.REGISTER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index INDIVIDUAL_PRIMARY = Internal.createIndex("PRIMARY", Individual.INDIVIDUAL, new OrderField[] { Individual.INDIVIDUAL.ID }, true);
        public static Index REGISTER_PRIMARY = Internal.createIndex("PRIMARY", Register.REGISTER, new OrderField[] { Register.REGISTER.REGISTERNO }, true);
    }
}
