/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables;


import com.jin.jooq.tables.tables.Individual;
import com.jin.jooq.tables.tables.Register;
import com.jin.jooq.tables.tables.records.IndividualRecord;
import com.jin.jooq.tables.tables.records.RegisterRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>cyui</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<IndividualRecord, Integer> IDENTITY_INDIVIDUAL = Identities0.IDENTITY_INDIVIDUAL;
    public static final Identity<RegisterRecord, Integer> IDENTITY_REGISTER = Identities0.IDENTITY_REGISTER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IndividualRecord> KEY_INDIVIDUAL_PRIMARY = UniqueKeys0.KEY_INDIVIDUAL_PRIMARY;
    public static final UniqueKey<RegisterRecord> KEY_REGISTER_PRIMARY = UniqueKeys0.KEY_REGISTER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<IndividualRecord, Integer> IDENTITY_INDIVIDUAL = Internal.createIdentity(Individual.INDIVIDUAL, Individual.INDIVIDUAL.ID);
        public static Identity<RegisterRecord, Integer> IDENTITY_REGISTER = Internal.createIdentity(Register.REGISTER, Register.REGISTER.REGISTERNO);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<IndividualRecord> KEY_INDIVIDUAL_PRIMARY = Internal.createUniqueKey(Individual.INDIVIDUAL, "KEY_individual_PRIMARY", Individual.INDIVIDUAL.ID);
        public static final UniqueKey<RegisterRecord> KEY_REGISTER_PRIMARY = Internal.createUniqueKey(Register.REGISTER, "KEY_register_PRIMARY", Register.REGISTER.REGISTERNO);
    }
}
