/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables;


import com.jin.jooq.tables.tables.Individual;
import com.jin.jooq.tables.tables.Register;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cyui
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cyui.individual</code>.
     */
    public static final Individual INDIVIDUAL = com.jin.jooq.tables.tables.Individual.INDIVIDUAL;

    /**
     * The table <code>cyui.register</code>.
     */
    public static final Register REGISTER = com.jin.jooq.tables.tables.Register.REGISTER;
}
