/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Individual implements Serializable {

    private static final long serialVersionUID = 352916620;

    private Integer   id;
    private String    userName;
    private String    userPassword;
    private String    userNiceName;
    private String    userImgUrl;
    private String    phoneNumber;
    private Date      userBirthday;
    private Timestamp utime;
    private Timestamp ctime;
    private String    role;

    public Individual() {}

    public Individual(Individual value) {
        this.id = value.id;
        this.userName = value.userName;
        this.userPassword = value.userPassword;
        this.userNiceName = value.userNiceName;
        this.userImgUrl = value.userImgUrl;
        this.phoneNumber = value.phoneNumber;
        this.userBirthday = value.userBirthday;
        this.utime = value.utime;
        this.ctime = value.ctime;
        this.role = value.role;
    }

    public Individual(
        Integer   id,
        String    userName,
        String    userPassword,
        String    userNiceName,
        String    userImgUrl,
        String    phoneNumber,
        Date      userBirthday,
        Timestamp utime,
        Timestamp ctime,
        String    role
    ) {
        this.id = id;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userNiceName = userNiceName;
        this.userImgUrl = userImgUrl;
        this.phoneNumber = phoneNumber;
        this.userBirthday = userBirthday;
        this.utime = utime;
        this.ctime = ctime;
        this.role = role;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserNiceName() {
        return this.userNiceName;
    }

    public void setUserNiceName(String userNiceName) {
        this.userNiceName = userNiceName;
    }

    public String getUserImgUrl() {
        return this.userImgUrl;
    }

    public void setUserImgUrl(String userImgUrl) {
        this.userImgUrl = userImgUrl;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Date getUserBirthday() {
        return this.userBirthday;
    }

    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    public Timestamp getUtime() {
        return this.utime;
    }

    public void setUtime(Timestamp utime) {
        this.utime = utime;
    }

    public Timestamp getCtime() {
        return this.ctime;
    }

    public void setCtime(Timestamp ctime) {
        this.ctime = ctime;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Individual (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userNiceName);
        sb.append(", ").append(userImgUrl);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(userBirthday);
        sb.append(", ").append(utime);
        sb.append(", ").append(ctime);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
