/*
 * This file is generated by jOOQ.
*/
package com.jin.jooq.tables.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Register implements Serializable {

    private static final long serialVersionUID = 1028650561;

    private Integer registerno;
    private String  registername;
    private Integer role;
    private Integer age;
    private String  address;
    private Integer status;

    public Register() {}

    public Register(Register value) {
        this.registerno = value.registerno;
        this.registername = value.registername;
        this.role = value.role;
        this.age = value.age;
        this.address = value.address;
        this.status = value.status;
    }

    public Register(
        Integer registerno,
        String  registername,
        Integer role,
        Integer age,
        String  address,
        Integer status
    ) {
        this.registerno = registerno;
        this.registername = registername;
        this.role = role;
        this.age = age;
        this.address = address;
        this.status = status;
    }

    public Integer getRegisterno() {
        return this.registerno;
    }

    public void setRegisterno(Integer registerno) {
        this.registerno = registerno;
    }

    public String getRegistername() {
        return this.registername;
    }

    public void setRegistername(String registername) {
        this.registername = registername;
    }

    public Integer getRole() {
        return this.role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Register (");

        sb.append(registerno);
        sb.append(", ").append(registername);
        sb.append(", ").append(role);
        sb.append(", ").append(age);
        sb.append(", ").append(address);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
